name: cdkversioncheck
on:
  push:
    branches:
      - master
  workflow_dispatch: {}
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      RELEASE: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch CDK versions
        run: |-
          echo "CDK_VERSION=$(curl --silent "https://api.github.com/repos/aws/aws-cdk/releases/latest" |
          grep '"tag_name":' |
          sed -E 's/.*"v([^"]+)".*/\1/')" >> $GITHUB_ENV
      - name: Synthesize project files
        run: |-
          yarn add projen
          CDK_VERSION=$CDK_VERSION npx projen
      - name: Push branch
        run: |- 
          git checkout -b bump/$CDK_VERSION
          git push -u origin bump/$CDK_VERSION
      - name: Set git identity
        run: |-
          git config user.name "Auto-bump"
          git config user.email "github-actions@github.com"
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: bump/$CDK_VERSION
          pr_title: Testing CDK version to $CDK_VERSION
          destination_branch: "master"
          github_token: ${{ secrets.PUSHABLE_GITHUB_TOKEN }}
    container:
      image: jsii/superchain